services:
  frontend:
    container_name: newsletter-frontend
    build: .
    ports:
      - "80:80"
    networks:
      - dev-network

  postgres:
    image: postgres:15
    container_name: newsletter_postgres
    env_file:
      - example.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network
  
  Email-Service:
    image: maildev/maildev
    container_name: email_service
    ports:
      - "1080:1080"  # Web UI
    expose:
      - 1025      # SMTP
    networks:
      - dev-network

  testnewsletter-service:
    image: ghcr.io/raullopezpenalva/newsletter-service:latest
    container_name: testnewsletter_service
    env_file:
      - example.env
    ports:
      - "8080:8080"
    networks:
      - dev-network

networks:
  dev-network:
    external: true

volumes:
  postgres_data: